### PR TITLE
Vars

### PR DESCRIPTION
**Pull request by gabfl**
Create a `vars.py` file to store website vars in order to allow an easier website customization.

Also adds the following features:
 - Support for multiple optional environments (with different document root, base path and URL).
 - Add support for template variables (`{{ some_var }}`) in page content
 - Add support to add new sections (beyond `blog` and `news`)
 - Add support to switch file extension (`.md`, `.html`...) in each section

### CODE REVIEW

**Comment by sunainapai** [comment]
I am afraid, I am not going to merge this pull request. The changes in this pull request are outside the scope of this project. There are no plans of offering a configurable makesite.py or a configurable website as part of this project. In this project:

- the code is the configuration, and
- the code is the documentation.

This project is meant for developers who may dive into the code and enhance it for their needs. An example website source is provided to get started quickly and then modify it as necessary.

For users who are looking for a completely configurable static site generator that requires little to no coding may find static site generators like Jekyll, Hugo, Pelican, etc. more useful. Alternatively, one may also improve this project like you have done to make it more configurable for personal use. But such enhancements will remain outside the scope of this project.

**Comment by gabfl** [comment]
No problem. I will keep them in my fork.

In any case, congrats on the project. It is simple and useful for a simple website. I used it to revamp my personal website (https://www.gab.lc/)

great job, congrats

**Comment by sunainapai** [comment]
Thank you. I am glad you find this project useful.

**Comment by sunainapai** [comment]
@gabfl, I have committed a minor stylesheet fix. Here is the commit: 4aad9f6b3fcc449f2baeb08aede7938c100127df. You might want to fix this in your website too in order to accurately center align the footer links.

**Comment by gabfl** [comment]
I just pulled the changes, thank you!

**Pull request closed without merging**
